
# setting up username , password for user
username=kollol645@mail.com	
password=Kalloldas@123

# Product search with below product name
searchtext=65inch TV

#Payment details screen data entry

cardnumber=1234567812343456
expirydate= 0223
securitycode=1234

